# Bảng luật chuyển mạch L3 tĩnh cho Pod 1 (Receiver / Analyzer)
# Cú pháp: <Địa chỉ IP CIDR> <Hành vi: FORWARD | DROP>

# Cho phép nhận các gói tin được chuyển tiếp từ Pod 0
172.217.0.0/16 FORWARD
142.250.0.0/16 FORWARD

# Mặc định nhận tất cả lưu lượng hợp lệ từ OVS
0.0.0.0/0 FORWARD
