apiVersion: v1
kind: Pod
metadata:
  name: dpdk-pod0
  labels:
    app: dpdk-l3-bridge
    role: forwarder
spec:
  restartPolicy: Never
  containers:
  - name: pod0-forwarder
    image: docker.io/library/pod0:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    command: ["/app/pod0_app"]
    args:
      - "-l"
      - "1-2"
      - "--file-prefix=pod0"
      - "--single-file-segments"
      - "--vdev=net_pcap0,rx_pcap=/data/balanced_traffic_sample.pcap,infinite_rx=1"
      - "--vdev=virtio_user0,path=/var/run/openvswitch/vhost-user-0,server=1"
    resources:
      requests:
        memory: "512Mi"
        hugepages-2Mi: "256Mi"
        cpu: "1"
      limits:
        memory: "1Gi"
        hugepages-2Mi: "256Mi"
        cpu: "2"
    volumeMounts:
    - name: pcap-data
      mountPath: /data
      readOnly: true
    - name: hugepages
      mountPath: /dev/hugepages
    - name: ovs-sockets
      mountPath: /var/run/openvswitch
  volumes:
  - name: pcap-data
    hostPath:
      path: /mnt/70E63C66E63C2EAA/Users/ADMIN/Desktop/coding/K8s-DPDK-L3-Bridge/data
  - name: hugepages
    hostPath:
      path: /dev/hugepages
  - name: ovs-sockets
    hostPath:
      path: /var/run/openvswitch
