#!/usr/bin/env bash
# ==============================================================================
# Script: gen_group_table.sh
# Mục đích: Phân tích manifests/ovs_flows.conf và sinh mã common/group_stats_table.h
#           để Pod 0 và Pod 1 dùng chung SSOT, phân loại theo 8 groups
# ==============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONF_FILE="$ROOT_DIR/manifests/ovs_flows.conf"
HEADER_FILE="$ROOT_DIR/common/group_stats_table.h"

if [ ! -f "$CONF_FILE" ]; then
    echo -e "\033[1;31m[LỖI] Không tìm thấy file cấu hình: $CONF_FILE\033[0m" >&2
    exit 1
fi

echo -e "\033[1;34m[Code-Gen] Đang sinh bảng group_stats_table.h từ manifests/ovs_flows.conf...\033[0m"

python3 - "$CONF_FILE" "$HEADER_FILE" << 'PYEOF'
import sys
import os
import re

conf_path = sys.argv[1]
header_path = sys.argv[2]

groups = []        # list of dict: {name, prio, action, is_drop, enum_name}
group_names = set()
group_map = {}     # name -> dict

filters = []       # list of dict: {name, group, proto, src_ip, dst_ip, src_port, dst_port, prio, group_idx}

section = None

with open(conf_path, "r", encoding="utf-8") as f:
    for line_num, line in enumerate(f, 1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        if "[GROUPS_SECTION]" in line:
            section = "GROUPS"
            continue
        elif "[FILTERS_SECTION]" in line:
            section = "FILTERS"
            continue

        if section == "GROUPS":
            # Syntax: [Group_Name],[Priority],[Action]
            parts = [p.strip() for p in line.split(",")]
            if len(parts) < 3:
                continue
            g_name, g_prio, g_act = parts[0], int(parts[1]), parts[2].upper()
            if g_name in group_names:
                print(f"[Code-Gen LỖI] Trùng lặp Group '{g_name}' tại dòng {line_num}", file=sys.stderr)
                sys.exit(1)
            group_names.add(g_name)
            
            enum_name = "GRP_" + re.sub(r'[^A-Za-z0-9_]', '_', g_name.replace("fg_l34_", "")).upper()
            g_obj = {
                "name": g_name,
                "prio": g_prio,
                "action": g_act,
                "is_drop": (g_act == "DROP"),
                "enum_name": enum_name,
                "index": len(groups)
            }
            groups.append(g_obj)
            group_map[g_name] = g_obj

        elif section == "FILTERS":
            # Syntax: [Filter_Name],[Group],[Proto],[SrcIP/Mask],[DstIP/Mask],[SrcPort],[DstPort]
            parts = [p.strip() for p in line.split(",")]
            if len(parts) < 7:
                continue
            f_name, f_grp, f_proto, f_src_ip, f_dst_ip, f_src_port, f_dst_port = parts[:7]
            if f_grp not in group_map:
                print(f"[Code-Gen LỖI] Filter '{f_name}' tham chiếu Group không tồn tại '{f_grp}' tại dòng {line_num}", file=sys.stderr)
                sys.exit(1)
            
            f_obj = {
                "name": f_name,
                "group_name": f_grp,
                "group_obj": group_map[f_grp],
                "proto": f_proto.lower(),
                "src_ip": f_src_ip,
                "dst_ip": f_dst_ip,
                "src_port": f_src_port,
                "dst_port": f_dst_port,
                "prio": group_map[f_grp]["prio"]
            }
            filters.append(f_obj)

# Sắp xếp filter theo thứ tự priority giảm dần (8 -> 7 -> ... -> 1)
filters.sort(key=lambda x: x["prio"], reverse=True)

def cidr_to_c(cidr_str):
    if cidr_str == "*" or cidr_str == "0.0.0.0/0":
        return ("0U", "0U")
    if "/" in cidr_str:
        ip_part, mask_part = cidr_str.split("/")
        depth = int(mask_part)
    else:
        ip_part = cidr_str
        depth = 32
    
    octets = [int(o) for o in ip_part.split(".")]
    ip_c = f"RTE_BE32(RTE_IPV4({octets[0]}, {octets[1]}, {octets[2]}, {octets[3]}))"
    
    if depth == 0:
        mask_c = "0U"
    else:
        mask_val = (0xFFFFFFFF << (32 - depth)) & 0xFFFFFFFF
        mask_c = f"RTE_BE32(0x{mask_val:08X}U)"
    return (ip_c, mask_c)

def proto_to_c(proto_str):
    if proto_str == "tcp":
        return "IPPROTO_TCP"
    elif proto_str == "udp":
        return "IPPROTO_UDP"
    elif proto_str == "icmp":
        return "IPPROTO_ICMP"
    else:
        return "0"

def port_to_c(port_str):
    if port_str == "*":
        return "0U"
    return f"RTE_BE16({int(port_str)}U)"

# Tạo file header
out = []
out.append("/* Auto-generated by scripts/gen_group_table.sh from manifests/ovs_flows.conf */")
out.append("/* DO NOT EDIT DIRECTLY. Edit manifests/ovs_flows.conf and rebuild. */")
out.append("")
out.append("#ifndef GROUP_STATS_TABLE_H")
out.append("#define GROUP_STATS_TABLE_H")
out.append("")
out.append("#include <stdint.h>")
out.append("#include <rte_byteorder.h>")
out.append("#include <rte_ip.h>")
out.append("")

# Groups Enum
out.append("/* Danh mục 8 Groups theo cấu hình SSOT */")
out.append("enum group_id {")
for g in groups:
    out.append(f"    {g['enum_name']} = {g['index']},")
out.append(f"    NUM_GROUPS = {len(groups)}")
out.append("};")
out.append("")

# Group Info Struct (chỉ giữ field runtime dùng thật: name/priority/action để in bảng)
out.append("struct group_info {")
out.append("    enum group_id id;")
out.append("    const char   *name;")
out.append("    uint32_t      priority;")
out.append("    const char   *action_str;")
out.append("};")
out.append("")

out.append("static const struct group_info GROUP_INFOS[NUM_GROUPS] = {")
for g in groups:
    out.append(f'    [{g["enum_name"]}] = {{ {g["enum_name"]}, "{g["name"]}", {g["prio"]}, "{g["action"]}" }},')
out.append("};")
out.append("")

# Filter Rule Struct (chỉ giữ field match + group_id; name/priority nằm ở comment từng rule)
out.append("struct filter_rule {")
out.append("    enum group_id group_id;")
out.append("    uint8_t       proto;     /* 0: any IP, 6: TCP, 17: UDP */")
out.append("    rte_be32_t    dst_net;   /* Network byte order */")
out.append("    rte_be32_t    dst_mask;  /* Network byte order */")
out.append("    rte_be32_t    src_net;   /* Network byte order */")
out.append("    rte_be32_t    src_mask;  /* Network byte order */")
out.append("    rte_be16_t    dst_port;  /* Network byte order */")
out.append("    rte_be16_t    src_port;  /* Network byte order */")
out.append("};")
out.append("")

out.append(f"#define NUM_FILTER_RULES {len(filters)}")
out.append("static const struct filter_rule FILTER_RULES[NUM_FILTER_RULES] = {")
for f in filters:
    g = f["group_obj"]
    dst_net_c, dst_mask_c = cidr_to_c(f["dst_ip"])
    src_net_c, src_mask_c = cidr_to_c(f["src_ip"])
    proto_c = proto_to_c(f["proto"])
    dst_port_c = port_to_c(f["dst_port"])
    src_port_c = port_to_c(f["src_port"])

    out.append(f'    /* Prio {f["prio"]} | {f["name"]} -> {g["name"]} ({g["action"]}) */')
    out.append("    {")
    out.append(f'        .group_id  = {g["enum_name"]},')
    out.append(f'        .proto     = {proto_c},')
    out.append(f'        .dst_net   = {dst_net_c},')
    out.append(f'        .dst_mask  = {dst_mask_c},')
    out.append(f'        .src_net   = {src_net_c},')
    out.append(f'        .src_mask  = {src_mask_c},')
    out.append(f'        .dst_port  = {dst_port_c},')
    out.append(f'        .src_port  = {src_port_c},')
    out.append("    },")

out.append("};")
out.append("")
out.append("#endif /* GROUP_STATS_TABLE_H */")

with open(header_path, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")

print(f"[Code-Gen] Đã sinh thành công {len(groups)} groups và {len(filters)} filters vào: {header_path}")
PYEOF
